### ISSUE TITLE
"invalid ActionID/OutputID" for Go tip

### ISSUE THREAD

**Issue by kevinburkesegment** [creachadair/gocache#1]
I'm running GOCACHEPROG with Go tip (as of writing, `go version devel go1.24-60299c2513 Wed Nov 20 23:14:02 2024 +0000 darwin/arm64`). 

Every attempt to cache anything yields the following output: 

```
16:59:48.100779 bc E PUT R:2, err put: invalid ActionID/OutputID, 100.375µs elapsed, DP:""
```

I edited the source code to just dump the entire contents of `req` and it looks like this, no OutputID:

```
req: &gocache.progRequest{ID:2, Command:"put", ActionID:[]uint8{0x8c, 0xf9, 0x1, 0x7b, 0xd8, 0x2c, 0xeb, 0xec, 0x6f, 0x30, 0x7, 0x88, 0x55, 0x61, 0x51, 0x86, 0x62, 0xa7, 0xfd, 0xa8, 0x3b, 0x7e, 0xb5, 0x69, 0x90, 0xd7, 0x5, 0x24, 0x97, 0xc, 0xa9, 0x8e}, OutputID:[]uint8(nil), Body:(*bytes.Reader)(0x140004c25a0), BodySize:2032}
```

**Comment by creachadair** [comment]
This won't currently work with tip, which has some API changes. Once it releases I'll update it.

**Comment by kevinburkesegment** [comment]
Ok... maybe `//go:build +1.24` or I could edit the error message?

**Comment by creachadair** [comment]
The problem is that the pre-1.24 code used "ObjectID" in the request message to the plugin. This disagreed with "OutputID" in the response. The Go team chose "OutputID" for the release version, and as a bridge the Go tool's implementation will (temporarily) accept both.

It probably isn't the end of the world to add that before the release, since it's still experimental anyway. 

Can you patch https://github.com/creachadair/gocache/pull/2 and see if it addresses your issue?
